### ISSUE TITLE
documentdb javadoc warning

### ISSUE THREAD

**Issue by ZhijunZhao** [Microsoft/azure-spring-boot-starters#114]
cd azure-spring-boot-starters\documentdb\spring-data-azure-documentdb
mvn package

There will be below warnings. 

[WARNING] Javadoc Warnings
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - @propertyDescription is an unknown tag.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - @propertyDescription is an unknown tag.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.
[WARNING] D:\azure-spring-boot-starters\documentdb\spring-data-azure-documentdb\src\main\java\com\microsoft\azure\spring\data\documentdb\core\mapping\BasicDocumentDbPersistentProperty.java:36: warning - Tags @propertyGetter, @propertySetter and @propertyDescription can only be used in JavaFX properties getters and setters.

**Comment by yungez** [comment]
fixed by PR #119
