### ISSUE TITLE
provide option to set azure-storage version in POM.xml 

### ISSUE THREAD

**Issue by rajadilipkolli** [Microsoft/azure-spring-boot-starters#12]
Provide option to set azure-storage version in POM.xml like how in spring boot we can override the default version

example if i want to use storage version 5.3.1 instead of 5.3.0 

I am expecting something like below in properties tag
<azure-storage>5.3.1</azure-storage>

**Comment by ZhijunZhao** [comment]
@rajadilipkolli Thanks for reporting this issue. Please verify whether the fix meets your requirement.

**Comment by rajadilipkolli** [comment]
I think it should work but is there a way to get snapshot version of this starter to verify?

**Comment by ZhijunZhao** [comment]
No. We need to do code sign. So, it's a little bit complicated process. 

But, you can always clone the repo and do `mvn install` to install all the starters to your local repo and test it.
