### ISSUE TITLE
ServiceBus QueueClient thread safety

### ISSUE THREAD

**Issue by MrPnut** [Microsoft/azure-spring-boot-starters#127]
According to the best practices document: https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements#reusing-factories-and-clients it states that QueueClient (and I'm assuming TopicClient and SubscriptionClient) are thread safe.

I understand that this may just be referring to the .NET SDK.

If this also applies to the Java SDK, then the beans in ServiceBusAutoConfig can be scoped as singleton instead of prototype.

**Comment by rajadilipkolli** [comment]
See last comment of #96 for the reason behind using prototype.

**Comment by ZhijunZhao** [comment]
@MrPnut Thanks for reporting this issue. You're right. I got the confirmation from the Java client author that it's thread-safe.
