### ISSUE TITLE
BOM should not provide dependency management for third party libraries

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot-starters#128]
It looks like you attempted to do something similar to `spring-boot-dependencies` which is the BOM of a "platform" (with stronger semantics). This project is more narrowed and its bom should only expose dependency management for the artifacts that the project produces (so in this case, azure artifacts). It should not have an opinion about third party dependencies (otherwise including that BOM in a project potentially overrides decisions that were made about them)

For versions that match the version of the project (everything in an ideal world except maybe Microsoft-specific jars that the starters require), I'd set them explicitly rather than using `${bom.version}`. If you're including the bom for Azure X.Y.Z, it should be X.Y.Z. and nothing else (Maven does not allow to override that property, which is good so it's not strictly necessary but the intent is more clear if you hardcode the current version).

Here is an example of BOM for reference: http://repo.spring.io/release/org/springframework/spring-framework-bom/4.3.8.RELEASE/spring-framework-bom-4.3.8.RELEASE.pom

**Comment by ZhijunZhao** [comment]
@snicoll Stéphane, thanks for all the valuable feedbacks. I'll resolve all of them ASAP. Then, I'll release them with a new version and update the Initializr PR.
