### ISSUE TITLE
AADAuthenticationFilterTest could not run

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot-starters#129]
`AADAuthenticationFilterTest` has a check before every method that does not validate. I guess that's an oversight of some kind.

**Comment by yaweiw** [comment]
@snicoll this is E2E test which requires some PII info e.g. client secret and jwt token etc. which can't be mocked in any way.

**Comment by snicoll** [comment]
I am not following. How do you run the test then? Why is it there?

**Comment by yaweiw** [comment]
In order to run the test, you need to provide a valid JWT token and AAD registered APP id and key. It's the test that verifies the core functionality of the filter.
