### ISSUE TITLE
Samples should not override what spring-boot-starter-parent provides by default

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot-starters#132]
The samples extends from `spring-boot-starter-parent` to (I suppose) reproduces what would happen with a blank app generated from start.spring.io.

If that's the intend, they shouldn't have override of maven plugin versions and dedicated `pluginsManagement`.  IMO, this is a bit confusing because the first objective is clearly not achieved so it's not obvious why they inherit from starter-parent. Not doing that would move the checkstyle and findbugs config in the parent, making the sample more succinct and easier to apprehend.

**Comment by ZhijunZhao** [comment]
Yes, the intention is to reproduce users' behavior. Earlier all the samples inherited from starter-parent, which saved all the checkstyle and findbugs config. But I think it's more important to consider users' behavior.
