### ISSUE TITLE
azure.token.acquire.timeout.seconds is wrongly namespaced

### ISSUE THREAD

**Issue by snicoll** [Microsoft/azure-spring-boot-starters#161]
If this property is keyvault specific, it should be under the `azure.keyvault` namespace IMO. If it isn't, I'd still rename it as the intend of the prefix is to define an origin for the feature rather than translating the property name itself.

**Comment by yungez** [comment]
thanks @snicoll Stephane for explaning that prefix is to define the origin of feature. No, those properties are not keyvault specific. Will rename them to follow the naming convention to indicate origin of the feature

**Comment by yungez** [comment]
closed by PR #167
