### ISSUE TITLE
mvn build failure in submodule folder due to no config/java.header

### ISSUE THREAD

**Issue by yungez** [Microsoft/azure-spring-boot-starters#46]
e:\javasrc\azure-spring-boot-starters\azure-documentdb-spring-boot-starter-sample>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Azure Document DB Spring Boot Starter Sample 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ azure-documentdb-spring-boot-starter-sample ---
[INFO] Deleting e:\javasrc\azure-spring-boot-starters\azure-documentdb-spring-boot-starter-sample\target
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (validate) @ azure-documentdb-spring-boot-starter-sample ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.263 s
[INFO] Finished at: 2017-07-24T18:16:58+08:00
[INFO] Final Memory: 20M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project azure-documentdb-spring-boot-starter-sample: Failed during checkstyle configuration: cannot initialize module Header - Unable to find: config/java.header -> [Help 1]

**Comment by rajadilipkolli** [comment]
I think issue is here https://github.com/Microsoft/azure-spring-boot-starters/blob/master/config/checkstyle.xml#L17 , this value should be relative
