### ISSUE TITLE
Library "ListBlobItem" Automatically Import

### ISSUE THREAD

**Issue by tyuanhang** [Microsoft/azure-spring-boot-starters#83]
![github issue](https://user-images.githubusercontent.com/29724116/28861540-f15df21a-7793-11e7-9b30-f52d6ab1d2aa.png)
When I type the above-mentioned code in VS code, the requisite library "com.microsoft.azure.storage.blob.ListBlobItem" can not be imported automatically. Why not remind the learners with a small tip here. In another way, can we merge the imports as below.
Original:
![wechat image_20170802150853](https://user-images.githubusercontent.com/29724116/28861702-9712e2a6-7794-11e7-9211-db99c3f508ad.png)
Modified:
![wechat image_20170802150921](https://user-images.githubusercontent.com/29724116/28861703-97c78f76-7794-11e7-8497-44ccc111576e.png)

**Comment by zhzy0077** [comment]
It's not recommended to use asterisk in `import` in order not to import unused classes.
