### ISSUE TITLE
rename DocumentDbRepositoryConfigurationExtensionUnitTest.java

### ISSUE THREAD

**Issue by rajadilipkolli** [Microsoft/azure-spring-boot-starters#89]
Consider renaming file name to shorter name, receiving filename too long error

![image](https://user-images.githubusercontent.com/24761580/28881138-d37f867e-77c4-11e7-9f8f-2cb1e75852aa.png)

**Comment by yungez** [comment]
unit test java file naming convention is testtargetclassname+UnitTest for easy tracking. since no issue found during ci, will close the issue for now. will refine the naming if met issue.
