### ISSUE TITLE
Exception when trying to use in a non-spring boot project

### ISSUE THREAD

**Issue by tschn** [Microsoft/azure-spring-boot-starters#91]
Seems the DocumentDbRepositoryFactoryBean needs a default constructor,  I am trying to use in a good old spring project (4.3.10.RELEASE) I get:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.data.documentdb.repository.support.DocumentDbRepositoryFactoryBean]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.microsoft.azure.spring.data.documentdb.repository.support.DocumentDbRepositoryFactoryBean.<init>()
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147)
	... 65 more
Caused by: java.lang.NoSuchMethodException: com.microsoft.azure.spring.data.documentdb.repository.support.DocumentDbRepositoryFactoryBean.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	... 66 more

**Comment by yungez** [comment]
@tschn , thanks for reporting the issue! could you pls share your pom.xml for further investigation? thanks in advance.

**Comment by tschn** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.test</groupId>
    <artifactId>nemo</artifactId>
    <packaging>war</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>${company.name} Website</name>
    <url>${webapp.baseUrl}</url>

    <profiles>
       
    </profiles>

    <prerequisites>
        <maven>3.1.0</maven>
    </prerequisites>

    <build>
        <finalName>${project.productline.id}</finalName>
        <defaultGoal>install</defaultGoal>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <delimiters>
                        <delimiter>@</delimiter>
                    </delimiters>
                    <useDefaultDelimiters>false</useDefaultDelimiters>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>clean-configuration</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo>Cleaning resource directory</echo>
                                <delete includeEmptyDirs="true">
                                    <fileset dir="${basedir}/src/main/resources"
                                             includes="**/Environment.properties **/Productline.properties **/Productline*.properties **/Marketing.properties **/Marketing*.properties"/>
                                </delete>
                                <echo>Cleaning template directory</echo>
                                <delete includeEmptyDirs="true">
                                    <fileset dir="${basedir}/src/main/webapp/WEB-INF/velocity"
                                             includes="**/*"/>
                                </delete>
                                <echo>Cleaning webapp resources directory</echo>
                                <delete includeEmptyDirs="true">
                                    <fileset dir="${basedir}/src/main/webapp/resources"
                                             includes="**/*"/>
                                </delete>
                            </tasks>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-variation-properties</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo>Copying environment-specific properties files from ${basedir}/src/main/variationPoints/${project.environment.id}
                                </echo>
                                <copy
                                        todir="${basedir}/src/main/resources"
                                        filtering="true"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/variationPoints/${project.environment.id}/"
                                            includes="**/*"
                                    />
                                </copy>
                                <echo>Copying productline-specific properties files from ${basedir}/src/main/variationPoints/${project.environment.id}
                                </echo>
                                <copy
                                        todir="${basedir}/src/main/resources"
                                        filtering="true"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/variationPoints/${project.productline.id}/productlineResources"
                                            includes="**/*"
                                    />
                                </copy>
                                <echo>Copying marketing-specific properties files from ${basedir}/src/main/variationPoints/${project.environment.id}
                                </echo>
                                <copy
                                        todir="${basedir}/src/main/resources"
                                        filtering="true"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/variationPoints/${project.productline.id}/marketingResources"
                                            includes="**/*"
                                    />
                                </copy>
                            </tasks>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-templates</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo>Copying common template files</echo>
                                <copy
                                        todir="${basedir}/src/main/webapp/WEB-INF/velocity"
                                        filtering="false"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/commonResources/velocity"
                                            includes="**/*"
                                    />
                                </copy>
                                <echo>Copying productline-specific template files from ${basedir}/src/main/variationPoints/${project.productline.id}
                                </echo>
                                <copy
                                        todir="${basedir}/src/main/webapp/WEB-INF/velocity"
                                        filtering="false"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/variationPoints/${project.productline.id}/velocity"
                                            includes="**/*"
                                    />
                                </copy>
                            </tasks>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-resources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo>Copying common resource files</echo>
                                <copy
                                        todir="${basedir}/src/main/webapp/resources"
                                        filtering="false"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/commonResources"
                                            excludes="**/velocity/**"
                                    />
                                </copy>
                                <echo>Copying productline-specific resource files from ${basedir}/src/main/variationPoints/${project.productline.id}
                                </echo>
                                <copy
                                        todir="${basedir}/src/main/webapp/resources"
                                        filtering="false"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/variationPoints/${project.productline.id}"
                                            includes="**/*"
                                            excludes="**/velocity/** **/productlineResources/**"
                                    />
                                </copy>
                            </tasks>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-misc</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo>Copying style images</echo>
                                <copy
                                        todir="${basedir}/target/classes/wro-target/styles/images"
                                        filtering="false"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/commonResources/styles/images"
                                            includes="**/*"
                                    />
                                </copy>
                                <echo>Copying ajax-solr files</echo>
                                <copy
                                        todir="${basedir}/target/classes/wro-target/scripts/ajax-solr"
                                        filtering="false"
                                >
                                    <fileset
                                            dir="${basedir}/src/main/commonResources/scripts/ajax-solr"
                                            includes="**/*"
                                    />
                                </copy>
                            </tasks>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>ro.isdc.wro4j</groupId>
                <artifactId>wro4j-maven-plugin</artifactId>
                <version>1.7.9</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <cssDestinationFolder>${basedir}/target/classes/wro-target/styles</cssDestinationFolder>
                    <jsDestinationFolder>${basedir}/target/classes/wro-target/scripts</jsDestinationFolder>
                    <contextFolder>${basedir}/src/main/webapp/</contextFolder>
                    <extraConfigFile>
                        ${basedir}/src/main/variationPoints/${project.environment.id}/wro.properties
                    </extraConfigFile>
                    <ignoreMissingResources>true</ignoreMissingResources>
                    <wroManagerFactory>ro.isdc.wro.maven.plugin.manager.factory.ConfigurableWroManagerFactory
                    </wroManagerFactory>
                    <groupNameMappingFile>${basedir}/src/main/resources/wromapping.properties</groupNameMappingFile>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.tomcat.maven</groupId>
                <artifactId>tomcat7-maven-plugin</artifactId>
                <version>2.2</version>
                <configuration>
                    <url>http://127.0.0.1:${appserver.port}/manager/text</url>
                    <username>tomcat</username>
                    <path>/${project.productline.id}</path>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.1</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>2.5</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${user.home}/${project.build.finalName}/index</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
                <version>2.3</version>
                <configuration>
                    <warSourceExcludes></warSourceExcludes>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                    <escapeString>\</escapeString>
                    <webResources>
                        <resource>
                            <directory>src/main/resources</directory>
                            <targetPath>WEB-INF/classes</targetPath>
                            <filtering>true</filtering>
                        </resource>
                    </webResources>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                        </manifest>
                        <manifestEntries>
                            <Implementation-Version>${project.version}</Implementation-Version>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <parallel>classes</parallel>
                    <threadCount>10</threadCount>
                    <testSourceDirectory>src/test</testSourceDirectory>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.18.1</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.zeroturnaround</groupId>
                <artifactId>jrebel-maven-plugin</artifactId>
                <version>1.1.5</version>
                <executions>
                    <execution>
                        <id>generate-rebel-xml</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-framework-bom</artifactId>
                <version>${spring.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.uvasoftware</groupId>
            <artifactId>scanii-java</artifactId>
            <version>2.11</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>5.3.1</version>
        </dependency>
        <dependency>
            <groupId>net.sf.jung</groupId>
            <artifactId>jung2</artifactId>
            <version>2.0.1</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>net.sf.jung</groupId>
            <artifactId>jung-graph-impl</artifactId>
            <version>2.0.1</version>
        </dependency>
        <dependency>
            <groupId>net.sf.jung</groupId>
            <artifactId>jung-algorithms</artifactId>
            <version>2.0.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity</artifactId>
            <version>${velocity.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-tools</artifactId>
            <version>2.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>servlet-api</artifactId>
                    <groupId>javax.servlet</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>velocity-tools</groupId>
            <artifactId>velocity-tools-view</artifactId>
            <version>${velocity.tools.view.version}</version>
        </dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
        </dependency>

        <dependency>
            <groupId>commons-beanutils</groupId>
            <artifactId>commons-beanutils</artifactId>
            <version>${commons.beanutils.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-collections</groupId>
            <artifactId>commons-collections</artifactId>
            <version>${commons.collections.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-fileupload</groupId>
            <artifactId>commons-fileupload</artifactId>
            <version>${commons.fileupload.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>${commons.io.version}</version>
        </dependency>
        <dependency>
            <groupId>commons-lang</groupId>
            <artifactId>commons-lang</artifactId>
            <version>${commons.lang.version}</version>
        </dependency>
        <dependency>
            <groupId>javassist</groupId>
            <artifactId>javassist</artifactId>
            <version>3.12.1.GA</version>
        </dependency>
        <dependency>
            <groupId>javax.mail</groupId>
            <artifactId>mail</artifactId>
            <version>${javamail.version}</version>
        </dependency>
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${log4j.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>mail</artifactId>
                    <groupId>javax.mail</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jms</artifactId>
                    <groupId>javax.jms</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jmxtools</artifactId>
                    <groupId>com.sun.jdmk</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jmxri</artifactId>
                    <groupId>com.sun.jmx</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>net.sf.ehcache</groupId>
            <artifactId>ehcache-core</artifactId>
            <version>${ehcache.version}</version>
        </dependency>
        <dependency>
            <groupId>net.sf.ehcache</groupId>
            <artifactId>ehcache-web</artifactId>
            <version>${ehcache.web.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-jaxrs</artifactId>
            <version>1.9.11</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.jackson</groupId>
            <artifactId>jackson-mapper-asl</artifactId>
            <version>1.9.11</version>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>jcl-over-slf4j</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
            <version>${spring.security.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
            <version>${spring.security.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
            <version>${spring.security.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-solr</artifactId>
            <version>2.0.3.RELEASE</version>
        </dependency>


        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spring-data-azure-documentdb</artifactId>
            <version>0.1.4</version>
        </dependency>
        

        <dependency>
            <groupId>org.tuckey</groupId>
            <artifactId>urlrewritefilter</artifactId>
            <version>${urlrewrite.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-email</artifactId>
            <version>1.3.3</version>
        </dependency>
        <dependency>
            <groupId>xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <version>2.11.0</version>
        </dependency>
    </dependencies>

    <properties>
        
        <project.environment.id>${project.activeProfiles[1].id}</project.environment.id>
        <project.productline.id>${project.activeProfiles[0].id}</project.productline.id>


        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <copyright.year>2015</copyright.year>
        <dao.framework>spring-data-solr</dao.framework>
        <web.framework>spring</web.framework>
        <amp.genericCore>true</amp.genericCore>
        <amp.fullSource>true</amp.fullSource>

        
        <bootstrap.version>3.3.5</bootstrap.version>
        <jquery.version>2.1.4</jquery.version>
        <jquery-cookie.version>1.4.1-1</jquery-cookie.version>
        <spring.version>4.3.10.RELEASE</spring.version>
        <spring.security.version>4.0.2.RELEASE</spring.security.version>
        <springmodules.validation.version>0.8</springmodules.validation.version>
        <commons.fileupload.version>1.3</commons.fileupload.version>
        <commons.io.version>2.4</commons.io.version>

        
        <mockito.version>1.9.5</mockito.version>
        <junit.version>4.11</junit.version>
        <wiser.version>1.2</wiser.version>

        
        <webtest.target>run-all-tests</webtest.target>

        <aspectj.version>1.7.4</aspectj.version>
        <commons.beanutils.version>1.8.3</commons.beanutils.version>
        <commons.collections.version>3.2.1</commons.collections.version>
        <commons.lang.version>2.6</commons.lang.version>
        <ehcache.version>2.6.6</ehcache.version>
        <ehcache.web.version>2.0.4</ehcache.web.version>
        <javamail.version>1.4.1</javamail.version>
        <jstl.version>1.2</jstl.version>
        <log4j.version>1.2.17</log4j.version>
        <slf4j.version>1.7.5</slf4j.version>
        <urlrewrite.version>4.0.4</urlrewrite.version>
        <velocity.version>1.7</velocity.version>
        <velocity.tools.view.version>2.0-beta1</velocity.tools.view.version>
        <wro4j.version>1.8.0</wro4j.version>
    </properties>
</project>

**Comment by tschn** [comment]
Am I missing something, how can I use this in a non-spring boot project?

**Comment by yungez** [comment]
@tschn , sorry for late response. after investigation, the dependency seems ok.  is there any autowire on your repository? could you pls share more code snippet on spring data documentdb configuration and repository class?

**Comment by yungez** [comment]
Hi @tschn , is the problem still valid? We've just released 0.1.5 version which contains some new features and bug fixing. could you give it a try?

**Comment by edwingustafson** [comment]
Adding 0.1.5 to the project yields an undeployable build for me. The error message below mentions `productDetailRepository`, which extends `SolrCrudRepository`. Is there something I have to do so that Spring Data Azure DocumentDB coexists with Spring Data Solr?

Again, this is happening with no Java changes at all, just adding the dependency to the POM.

```Aug 22, 2017 3:33:59 PM org.springframework.web.context.ContextLoader initWebApplicationContext
SEVERE: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'productDetailRepository': Could not resolve matching constructor (hi
  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:236)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getSingletonFactoryBeanForTypeCheck(AbstractAutowireCapableBeanFactory.jav
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryBean(AbstractAutowireCapableBeanFactory.java:796)
  at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:543)```

**Comment by yungez** [comment]
@edwingustafson  thanks for reporting the issue. Could you pls share your pom config or spring version, spring-data-solr version? thanks in advance. from the error, it seems there's conflict on spring version used by spring-data-azure-document. while I tried spring-data-azure-document data with spring 1.4.3.release and 1.5.6.release, no error met.

**Comment by edwingustafson** [comment]
@yungez updating `spring-data-solr` from version `2.0.3.RELEASE` to `2.1.6.RELEASE` built a deployable WAR. Thank you for quick response with finger squarely on the problem.

**Comment by tschn** [comment]
this worked after updating spring-data-solr version and creating separate packages for spring-data-solr and spring-data-azure-documentdb classes
